### ISSUE TITLE
Can't Save

### ISSUE THREAD

**Issue by cfjedimaster** [swyphcosmo/vscode-spellchecker#15] opened 2016-11-02 19:55 UTC
_From @cfjedimaster on November 2, 2016 17:35_

- VSCode Version: 1.6.1
- OS Version: Win 10 Pro

I was working w/ Code all day today and all of a sudden, I can't save a file. I don't get a visual error, and the app seems completely fine in every other aspect. But the 'dirty' indicator won't go away and the file never actually saves. 

I opened up dev tools and see this:

C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\vscode-textmate\release\main.js:1716 [1] - Grammar is in an endless loop - Grammar pushed & popped a rule without advancingscanNext @ C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\vscode-textmate\release\main.js:1716

_Copied from original issue: Microsoft/vscode#14864_

**Comment by cfjedimaster** [comment] 2016-11-02 19:55
Actually I'm wrong. Menu items still work, but I can't select any file.

**Comment by cfjedimaster** [comment] 2016-11-02 19:55
I went to Task Manager to try to kill Code. It prompted me to save again so I figured, why not. I got multiple errors then. They include:

Error from the extension host: channel closed
Extension host terminated unexpectedly. Please reload the window to recover.
Error from the extension host: write EPIPE

**Comment by cfjedimaster** [comment] 2016-11-02 19:55
After killing Code and restarting it, I can recreate the issue. I am editing an HTML file. I had 2 form fields. I added value="stuff" to them and Code breaks.

**Comment by cfjedimaster** [comment] 2016-11-02 19:55
Nope, not related to that line. Any edit, even adding a new line, causes the issue. No errors show in devtools.

**Comment by cfjedimaster** [comment] 2016-11-02 19:55
And it's not HTML related at all. Even a JS file has the same behavior now. Wow - I'm at a loss now.

**Comment by cfjedimaster** [comment] 2016-11-02 19:55
Wow, I rebooted, and I still can't save files. :(

**Comment by cfjedimaster** [comment] 2016-11-02 19:55
Ah no - sorry - it was just a bit slow. So yeah, rebooting did help.

**Comment by cfjedimaster** [comment] 2016-11-02 19:55
And I'm back to it being broken. :( I went back to my html file, added those value="..." things again, and I managed to make it break. Nothing in console. But can't save.

**Comment by cfjedimaster** [comment] 2016-11-02 19:55
So I had Code open and was ignoring it while on a phone call. The file was in it's dirty state, not being able to save. While I was on the phone, the UI popped up two issues:

Error from the extension host: channel closed
Extension host terminated unexpectedly. Please reload the window to recover.

Devtools had 3 errors:

messageService.ts:128 Extension host terminated unexpectedly. Please reload the window to recover.e.doShow @ messageService.ts:128e.show @ messageService.ts:107(anonymous function) @ threadService.ts:267emitTwo @ events.js:106emit @ events.js:191ChildProcess._handle.onexit @ internal/child_process.js:215

threadService.ts:271 Extension host terminated unexpectedly. Code:  3  Signal:  null(anonymous function) @ threadService.ts:271emitTwo @ events.js:106emit @ events.js:191ChildProcess._handle.onexit @ internal/child_process.js:215

messageService.ts:128 Error from the extension host: channel closede.doShow @ messageService.ts:128e.show @ messageService.ts:107(anonymous function) @ threadService.ts:257emitOne @ events.js:96emit @ events.js:188target.send @ internal/child_process.js:544a.postMessage @ threadService.ts:322(anonymous function) @ threadService.ts:66t @ ipcRemoteCom.ts:257_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

**Comment by cfjedimaster** [comment] 2016-11-02 19:55
So I disabled one extension at a time and it seems to have been the spellchecker extension. I'd like to post this bug on their repo - let me figure out how to do that before I close this one.

**Comment by cfjedimaster** [comment] 2016-11-02 19:55
_From @rebornix on November 2, 2016 18:38_

ppl ran into similar issues in #14436 and @jrieken might be interested in @cfjedimaster 's repro steps.

**Comment by swyphcosmo** [comment] 2016-11-02 20:45
Those files you mention aren't part of this extension. I have seen it do some weird things so I would like to try to reproduce it. Would you provide a list of extensions that you have installed and if you can provide a zip file containing the workspace you're working with, that would be very helpful. If not, what other types of files do you have open? This extension doesn't do anything with html and js files unless you specifically tell it to using the settings.json file. So the not saving could be a symptom of a problem with another file.

**Comment by cfjedimaster** [comment] 2016-11-02 20:48
Shoot. I did notice it go away _immediately_ after removing your extension, but sorry if I misfired. The code is a bit messy now, but you can find it here: https://github.com/cfjedimaster/StrongLoopDemos/tree/master/filetest/client

It was the index.html file.

**Comment by swyphcosmo** [comment] 2016-11-03 17:52
I was able to track down what's going on. This plugin was creating the issue of not being able to save, but the real cause of it is due to a change in VSCode itself. When the spellchecker starts, it loops through all open documents and spell checks them. If you just had `index.html` open, it would skip that file since the type `html` isn't checked by default. For whatever reason, VSCode now stores an additional document with the same content as `index.html`, but it has `languageId = 'plaintext'` and `uri.scheme = 'private'`. The latter is typically set to `'file'`. 

Because of this, the spell checker tries to spell check your html file, but it gets stuck trying to find suggestions for the sha256 on line 58 of your file. Finding word suggestions is a costly process because it tries putting different letters into each letter position, then checks the dictionary for that word. With typical words, this cost is minimal, but the sha is a very large word. Because the spell checker is still trying to find suggestions, vscode won't let you save.

I'm implementing a couple things to help keep this contained in the future. First, the spellchecker will ignore any files that have `uri.scheme != 'file'`. This will make sure that the html file does not get checked in the first place. Second, if a word contains a number character, suggested correct words will not be searched for.

I just pushed v1.2.2 to the marketplace that fixes these issues.

Please let me know if it works for you so that we can close the issue.

**Comment by cfjedimaster** [comment] 2016-11-03 18:00
Seems good, thanks!

**Closed as completed** 2016-11-03 18:04 UTC

**Comment by jrieken** [comment] 2016-11-04 08:36
@swyphcosmo FYI - we have these shadow documents ever since when something is under source control. Those files represent the baseline version against which operations like compare and dirty-diff annotations work. Checking against the `scheme` is the right thing to do.

**Comment by swyphcosmo** [comment] 2016-11-04 15:01
@jrieken Thanks for the additional information. For whatever reason, I never ran into them before. I'm glad I got it handled in the proper way.
