### ISSUE TITLE
The spellchecker hangs other extensions in long documents

### ISSUE THREAD

**Issue by jmalarcon** [swyphcosmo/vscode-spellchecker#40] opened 2017-03-17 13:29 UTC
Hi:

If you open a long Markdown document and spellchecker kicks in, it takes many many seconds to review the document and meanwhile the rest of the extensions don't work: you can't previe the document, use shortkeys to apply format, etc...

Is there any chance to change the extension to be non-blocking? (if that makes sense in this context).

Thanks!

Keep up the good work!

**Comment by swyphcosmo** [comment] 2017-03-17 18:09
How long of a document are you having issues with? I just tried it with this [sample document](http://daringfireball.net/projects/markdown/syntax.text) which on a very new desktop took a while for the extension to check, but I was able to preview the document immediately after opening it. Can you open the developer console (Help -> Toggle Developer Tools) to see if any errors are showing up?

**Comment by jmalarcon** [comment] 2017-03-17 18:49
Hi Michael:

Not very long. In fact far less than the sample you mention (like 20% of its length). It takes almost 50 seconds to show the preview for the daringfireball sample document. I have some other extensions installed but if I disable the spellchecker everything goes fast immediately.

You can see it happening in this short video I've just recorded:

https://www.youtube.com/watch?v=0NBC2UyMwPg&

Notice that when I disable the extension everything goes smoothly. 

Any ideas on why this could be happening?

Thanks!

**Comment by swyphcosmo** [comment] 2017-03-17 19:02
Very interesting. I don't seem to have that preview button. How did you get that? When I use CTRL+SHIFT+V, it comes up automatically.

I also don't use the MiniMap. I just tried enabling it, and that seems to be the cause of the issue. With the MiniMap enabled, the Markdown Preview doesn't show up until after spell checking is complete. This might be an issue for the VSCode team instead of me.

**Comment by jmalarcon** [comment] 2017-03-17 19:13
Hi again:

Well, that button is enabled by default in VSCode since several versions ago. I don't know how to even disable it. In fact I use the CTRL+SHIFT+V shortcut too but I pressed the button in the video to be more evident on what I was doing.

The MiniMap has nothing to do either. I enabled it in the latest update (I find it helpful) but the problem happens without it too (I've already checked it). It has been happening since the first time I installed the spell checker :-?

I have the latest VSCode version:

![image](https://cloud.githubusercontent.com/assets/1775322/24058929/3ef45144-0b4d-11e7-94c6-fc5180a89920.png)

and this is my list of plugins:

![image](https://cloud.githubusercontent.com/assets/1775322/24059090/f2d16c88-0b4d-11e7-8ee3-7ea9cb49aa5f.png)

Another thing that happens is that I have your plugin settings in the general settings for the editor, like this:

![image](https://cloud.githubusercontent.com/assets/1775322/24059132/22fd77f8-0b4e-11e7-80fb-d213f89143d9.png)

and they are not correctly recognized. Can this have something to do with the issue?

Thanks again.

**Comment by swyphcosmo** [comment] 2017-03-17 19:37
Okay, hmmm. MiniMap fixed the problem for me. I would guess that one of the other extensions is having a bad interaction with the spell checker. Perhaps you can try switching them all extensions off except for the spell checker, and then enabling them individually to see when the issue pops up. This will help give me more information to figure out how I can make the spell checker behave properly with other extensions.

The warnings in the settings.json aren't an issue. I didn't use an "official" way to add settings into the file because I couldn't find a way to do it. However, I just installed an extension yesterday that did add settings without the warnings so I'm going to be digging into that one to see what they did.

**Comment by jmalarcon** [comment] 2017-03-18 09:34
I've tried it today: I've disabled all other extensions and left only the spell checker. I disabled the MiniMap too. The same thing happens again 😞 

I even have deleted all the settings, leaving the editor as it comes out of the box: as soon as I install the spell checker the same thing happens again even in that case.

To sum up: a clean VSCode install with no specific settings and only the spell checker plugin installed. Open the same file and the locking happens. I've tried it in my two computers with the same results. So I think clearly is the spell checker plugin. 

The problem is that maybe is some combination of hardware and software, I don't know... I have SSD disks in my two computers and Windows 10 Professional in English with the latest updates, but that is the only  things they share.

It will be useful to know if more people are experiencing the same problem.

If you have any ideas they'll be welcome. If not, thanks anyway for your great extension and your support. Microsoft should have it included by default in VSCode :-)

Cheers!

**Comment by swyphcosmo** [comment] 2017-04-03 07:43
I just uploaded a new version of the extension. I removed a loop which processes all files when the extension starts. Let me know if you this might fix the problem. If not, I'll dig deeper into possible solutions.

**Comment by jmalarcon** [comment] 2017-04-03 07:50
Hey Michael, it seems to go faster. Still blocks a little bit at the beginning but definitely seems to go faster overall :-)

Thanks for your support!

**Comment by swyphcosmo** [comment] 2017-04-13 18:38
Glad it works better. I'm going to close the issue, but feel free to open it back up if you run into the same issue again.

**Closed as completed by swyphcosmo** 2017-04-13 18:38 UTC
