### ISSUE TITLE
VSCode crash with Facebook auth token string

### ISSUE THREAD

**Issue by albertogasparin** [swyphcosmo/vscode-spellchecker#5] opened 2016-08-04 13:05 UTC
I have a `.env` file with several of tokens in it. Everything was fine until I added a FB token like:

```
FB_AUTH_TOKEN=EAAPKZCriJaEABNMWhdZAZCKrNsS9AJ8cX1Y1wyVLfGvMIwpLKlmw0Ox9vNoSkMCqwptkb0Oj9QyyA0lG0zflySEdiN1TiNpHSqPXZCp9RVJZryv7LzjZAEOXGecmo5YbgHZAqZAt07VrE3nlPZaeYGxLnZA32KYXZAWrCZD
```

Now, every time I preview that file in VSCode it end up crashing after a bit. Uninstalling your extension restores VSCode stability. I have no other extension parsing the `.env` file.
- Platform: OSX
- VSCode version: 1.3.1
- Extension version: 1.1.5

**Comment by swyphcosmo** [comment] 2016-08-04 15:46
Great catch! The issue turned out to be an issue with how the `hunspell-spellchecker` tries to build suggestions to the error. The authentication token you provided is 168 characters long. The first step is to transpose adjacent characters. Then, it creates permutations of the word by placing every other letter of the alphabet into each character slot. For a word of 168 characters, this list grows until the node has consumed all of the system memory. This is the cause of the crash. 

I've created a fix for this to limit the word suggestions to words shorter than 50 characters (the longest word in the English dictionary is 45 characters). I will also add the ability to ignore certain file extensions. This would let you remove `.env` files from being checked by the extension. 

I'll close this issue once a new version has been published.

**Comment by swyphcosmo** [comment] 2016-08-04 16:17
Version 1.1.6 has been published. I'm not sure how to force vscode to update the extension list. You might need to uninstall the extension, and then reinstall it.

**Closed as completed by swyphcosmo** 2016-08-04 16:17 UTC
Labels: bug

**Comment by albertogasparin** [comment] 2016-08-07 13:07
Amazing! Thanks a lot, new version worked like a charm 👍
